Repository VacuumORG/forum_vacuum, pull requests merged in 2023-05, with the labels that each got.

#36 Adicionando Alias para acessar a pasta LIB
  src/pages/api/topics.ts
  tsconfig.json
Labels: bug

#32 fix/padronizando o acesso ao supabase
  lib/connection.ts
  src/pages/api/db.ts
  src/pages/api/topics.ts
  tsconfig.json
Labels: enhancement, good first issue

#31 feat/new user avatar upload component
  src/components/SignUpAvatar/index.tsx
Labels: enhancement

#28 fix/supabase query topics
  .gitignore
  src/pages/api/v1/topics/index.ts
Labels: enhancement

#24 feat/new topic component
  public/AvatarImage.png
  public/anexo-black.svg
  public/anexo.svg
  public/picture-black.svg
  public/picture.svg
  src/components/NewPostForm/index.tsx
  src/components/NewTopic/index.tsx
  src/components/TextField/index.tsx
  src/styles/theme.css
Labels: enhancement

#39 fix\updating-readme-structure
  README.md
Labels: documentation, enhancement

#41 feat/add structure models
  models/auth/LoginModel.ts
  models/topics/TopicModel.ts
  src/pages/api/v1/auth/index.ts
  src/pages/api/v1/topics/index.ts
Labels: documentation, enhancement

#43 feat/create-categories-route
  src/pages/api/v1/categories/index.ts
Labels: enhancement, backend

#44 feat/create get all tags route
  src/pages/api/v1/tags/index.ts
Labels: enhancement, backend

#46 feat/add params in route topics
  models/topics/TopicModel.ts
  package.json
  src/pages/api/v1/topics/index.ts
  yarn.lock
Labels: enhancement, backend

#49 fix/converting-statusCode-into-importable-module
  lib/statusCode.ts
  src/pages/api/v1/auth/index.ts
  src/pages/api/v1/categories/index.ts
  src/pages/api/v1/tags/index.ts
  src/pages/api/v1/topics/index.ts
Labels: bug, backend

#50 feat/function to generate random number
  utils/randomNumberGenerator.ts
Labels: enhancement

#47 Feat/mount page when user not logged
  src/components/EventWarning/index.tsx
  src/components/Menu/index.tsx
  src/components/Modal/index.tsx
  src/components/SignUp/index.tsx
  src/components/TagsInHigh/index.tsx
  src/components/TextField/index.tsx
  src/components/Topic/index.tsx
  src/components/UserArea/index.tsx
  src/pages/index.tsx
  src/styles/theme.css
Labels: frontend

#48 feat/added code quality check
  .github/workflows/codeql.yml
Labels: enhancement, help wanted

#57 Feat/code auth box component
  src/components/CodeAuthBox/index.tsx
  src/components/Modal/index.tsx
  src/styles/theme.css
Labels: enhancement, frontend

#63 build: added node version suppoted
  package.json
Labels: bug, backend

#64 style: config theme in tailwind
  tailwind.config.js
Labels: bug, frontend

#55 feat/list-all-topics-for-a-user
  models/profile/index.ts
  src/pages/api/v1/profile/index.ts
  src/pages/api/v1/profiles/[id]/topics/get.ts
Labels: enhancement, backend

#56 fix: turn the request private
  src/pages/api/v1/tags/list.ts
Labels: bug, backend

#61 fix/fixing-the-model-name-c
  models/topic/index.ts
  src/pages/api/v1/topics/get.ts
Labels: bug, backend

#67 feat/api-route-protection-pattern
  docs/ProtectedAPI.md
  lib/authGuard.ts
  lib/httpVerbGuard.ts
Labels: enhancement, backend

#62 feat/route-to-get-information-from-a-topic-c
  models/topic/index.ts
  src/pages/api/v1/topics/[id]/get.ts
Labels: enhancement, backend

#73 feat/add API endpoint for profile creation and update profile model
  models/auth/index.ts
  models/profile/index.ts
  src/pages/api/v1/profiles/create.ts
Labels: enhancement, backend

#77 feat/add TokenResponseModel interface
  models/auth/index.ts
Labels: documentation, backend

#72 fix: fix bug when running codeql and tests
  .github/workflows/codeql.yml
  .github/workflows/tests.yaml
Labels: bug

#81 fix-feat/recreating-all-routes-from-the-profiles-set
  src/pages/api/v1/profiles/[id]/comments.ts
  src/pages/api/v1/profiles/[id]/index.ts
  src/pages/api/v1/profiles/[id]/topics.ts
  src/pages/api/v1/profiles/[id]/topics/get.ts
  src/pages/api/v1/profiles/create.ts
  src/pages/api/v1/profiles/index.ts
  src/pages/api/v1/profiles/spec.md
  utils/fakeProfilesCreate.js
Labels: bug, enhancement, backend

#82 feat/add-sql-to-create-tables
  docs/sql/create_tables.sql
Labels: documentation, backend

#84 Feat/get all tags route
  models/tag/index.ts
  src/pages/api/v1/tags/[id]/index.ts
  src/pages/api/v1/tags/index.ts
  src/pages/api/v1/tags/spec.md
Labels: enhancement, backend

#86 feat/criação de rotas relacionadas a categoria
  src/pages/api/v1/categories/[id]/index.ts
  src/pages/api/v1/categories/index.ts
Labels: enhancement, backend

#87 feat/Criação de rota para gerenciar comentários
  src/pages/api/v1/comments/[id]/index.ts
  src/pages/api/v1/comments/spec.md
Labels: enhancement, backend

#88 fix sub-routes
  src/pages/api/v1/profiles/[id]/comments/index.ts
  src/pages/api/v1/profiles/[id]/topics/index.ts
Labels: bug, backend

#91 feat/login-route
  src/pages/api/v1/auth/login/index.ts
Labels: enhancement, backend

#92 feat/reset-password-flow
  src/pages/api/v1/auth/password-reset/finish/index.ts
  src/pages/api/v1/auth/password-reset/index.ts
Labels: bug, enhancement, backend

#95 fix: back button in the signup modal
  src/components/SignUp/index.tsx
Labels: bug, frontend

#97 fix/fixed modals rendering
  src/components/CodeAuthBox/index.tsx
  src/components/Login/index.tsx
  src/components/Modal/index.tsx
  src/components/SignUp/index.tsx
  src/components/SignUpAvatar/index.tsx
  src/pages/index.tsx
Labels: bug, frontend

#98 feat: add forum post component
  src/components/NewPost/index.tsx
Labels: enhancement, frontend

#99 feat: create components CommentsSessions, CommentList and UpvoteDownvote
  src/components/CommentList/CommentList.tsx
  src/components/CommentsSessions/index.tsx
  src/components/UpvoteDownvote/index.tsx
Labels: enhancement, frontend

#101 fix: TagsInHigh component refactoring
  src/components/TagsInHigh/index.tsx
  src/pages/home/index.tsx
  src/pages/index.tsx
  src/styles/theme.css
Labels: bug, frontend

#94 feat/create route topics/[id]/views
  .env.example
  src/pages/api/v1/topics/[id]/views/index.ts
Labels: enhancement, backend

#96 feat: create update likes route
  src/pages/api/v1/topics/[id]/likes/index.ts
Labels: enhancement, backend

#104 feat: create components TagList, Tag
  src/components/Tag/index.tsx
  src/components/TagsList/index.tsx
  src/pages/index.tsx
Labels: frontend

#106 Feat/popover
  package.json
  src/components/UserArea/UserOptions/index.tsx
  src/components/UserArea/index.tsx
  yarn.lock
Labels: enhancement, help wanted, question, frontend

#107 Create Markdown component
  src/components/Markdown/index.tsx
Labels: enhancement, frontend

#109 Feat/response comment
  src/components/CommentList/CommentList.tsx
  src/components/CommentsSessions/index.tsx
  src/components/Markdown/index.tsx
  src/styles/theme.css
Labels: enhancement, frontend

#111 Feat/axios config
  .env.example
  package.json
  src/api/api.ts
  src/api/services/profileService.ts
  src/api/services/userService.ts
  src/components/SignUp/index.tsx
  yarn.lock
Labels: enhancement, frontend

#113 Feat/create topic routes
  models/topic/index.ts
  src/pages/api/v1/topics/[id]/likes/index.ts
  src/pages/api/v1/topics/[id]/views/index.ts
  src/pages/api/v1/topics/index.ts
  src/pages/api/v1/topics/spec.md
Labels: enhancement, backend

#114 Feat/front/user profile page
  public/edit-circle.svg
  public/unsplashAvatar.jpg
  src/components/Button/index.tsx
  src/components/ProfileSettings/BannerProfile/index.tsx
  src/components/ProfileSettings/EditUserContainer/ChangeNameForm.tsx
  src/components/ProfileSettings/EditUserContainer/ChangePasswordForm.tsx
  src/components/ProfileSettings/EditUserContainer/index.tsx
  src/components/ProfileSettings/Sidebar/index.tsx
  src/components/ProfileSettings/UploadAvatar/index.tsx
  src/components/ProfileSettings/index.tsx
  src/components/TextField/ProfileSettingsTextField/index.tsx
  src/components/UserArea/UserOptions/index.tsx
  src/components/UserLogged/index.tsx
  src/pages/user-profile.tsx
Labels: enhancement, frontend

#116 Feat/auth route
  package.json
  src/api/services/auth.ts
  src/components/Login/index.tsx
  src/pages/index.tsx
  yarn.lock
Labels: enhancement, frontend

#124 feat: integration CommentsSessions
  src/components/CommentList/CommentList.tsx
  src/components/CommentsSessions/index.tsx
  src/components/Markdown/index.tsx
Labels: enhancement, frontend

#125 fix: Correction bug in 'TagsInHigh'
  src/components/TagsInHigh/index.tsx
  src/pages/home/index.tsx
  src/styles/theme.css
Labels: bug, frontend

#126 Feat/topics service
  models/comments/index.tsx
  src/api/services/topicsService.ts
  src/components/Topic/index.tsx
  src/pages/home/index.tsx
  src/pages/index.tsx
Labels: enhancement, frontend

#127 feat: Integration all functions topicsService
  src/pages/index.tsx
Labels: enhancement, frontend

#128 fix: forms and textfields
  src/api/services/tagsInHigh.ts
  src/components/Menu/index.tsx
  src/components/ProfileSettings/ChangeAvatarForm/index.tsx
  src/components/ProfileSettings/EditUserContainer/ChangeNameForm.tsx
  src/components/ProfileSettings/EditUserContainer/ChangePasswordForm.tsx
  src/components/ProfileSettings/UploadAvatar/index.tsx
  src/components/ProfileSettings/index.tsx
  src/components/SignUp/index.tsx
  src/components/SignUpAvatar/index.tsx
  src/components/TextField/ProfileSettingsTextField/index.tsx
  src/pages/user-profile.tsx
Labels: enhancement, frontend
